eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    password: arjndb
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
